story_9/authentication/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from .views import index, signup, signin, signout

app_name = 'authentication'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('signin/', signin, name='signin'),
    path('signout/', signout, name='signout'),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

story_9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('story_9.authentication.urls')),
]

story_9/authentication/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class UserAccount(AbstractUser):
   email = models.EmailField(unique=True)
   profile_image = models.ImageField(null=True, blank=True, upload_to="profile_image/")

   REQUIRED_FIELDS = ['email', 'password']

   class Meta:
      verbose_name = 'user'
      verbose_name_plural = 'users'

story_9/authentication/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django import forms

class RegisterForm(UserCreationForm):
    
    class Meta: 
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'profile_image']

story_9/authentication/views.py
from django.shortcuts import redirect, render
from .forms import RegisterForm
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout
from django.contrib.auth import login as auth_login


def index(request):
    response = {}
    if request.user.is_authenticated: 
        response['username'] = request.user.get_username()
        response['email'] = request.user.email
        response['fullname'] = request.user.get_full_name()
        response['profile_image'] = request.user.profile_image
    return render(request, 'authentication/index.html', response)

def signup(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Account created successfully!")
            return redirect('authentication:signin')
    form = RegisterForm(request.POST or None)
    response = {'register_form': form}
    return render(request, 'authentication/signup.html', response)

def signin(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            auth_login(request, user)
            # messages.success(request, "You have logged in successfully!")
            return redirect('authentication:index')
        else:
            messages.error(
                request, "No account can be found, please check your credentials or register first if you have not done so")
            return redirect('authentication:signin')
    response = {'login_form': form}
    return render(request, 'authentication/signin.html', response)

def signout(request):
    logout(request)
    return redirect('authentication:index')

story_9/authentication/templates/authentication/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8" />
    <title>Authentication</title>
    <meta name="description" content="A simple authentication width Django" />
    <meta name="author" content="Teofanus Gary Setiawan" />

    <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;800&display=swap"
      rel="stylesheet"
    />

    <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'authentication/css/index.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'authentication/js/index.js' %}"></script>

    <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="icon" type="image/png" href="{% static 'images/Logo.png' %}" />
  </head>
  <body>
    <header
      id="title"
      class="text-center flex flex-col justify-center items-center min-h-screen p-4"
    >
      <div class="flex-grow flex flex-col justify-center items-center gap-y-4">
        <p class="animate-pulse text-5xl sm:text-8xl font-bold">
          Hello, {% if user.is_authenticated %}{{ user.username }}!{% else %}Anonymous!{% endif %}
        </p>
        {% if user.is_authenticated %}
        <a
          href="{% url 'authentication:signout' %}"
          class="py-1 px-2 rounded-md"
        >
          Sign Out
        </a>
        {% else %}
        <div class="flex gap-x-4">
          <a
            href="{% url 'authentication:signup' %}"
            class="py-1 px-2 rounded-md"
          >
            Sign Up
          </a>
          <a
            href="{% url 'authentication:signin' %}"
            class="py-1 px-2 rounded-md"
          >
            Sign In
          </a>
        </div>
        {% endif %}
      </div>
      <div
        class="text-center flex flex-col items-center gap-y-2 {% if not user.is_authenticated %}hidden{% endif %}"
      >
        <p class="text-base">Scroll down to see your profile</p>
        <a href="#profile" class="focus:outline-none" id="arrow">
          <svg
            class="animate-bounce w-6 h-6 text-amber-900"
            fill="none"
            stroke-linecap="round"
            stroke-linejoin="round"
            stroke-width="2"
            viewBox="0 0 24 24"
            stroke="currentColor"
          >
            <path d="M19 14l-7 7m0 0l-7-7m7 7V3"></path>
          </svg>
        </a>
      </div>
    </header>
    <section
      id="profile"
      class="{% if not user.is_authenticated %}hidden{% endif %} pt-16 min-h-screen"
      style="scroll-snap-align: start"
    >
      <div
        class="text-2xl rounded h-full w-full flex flex-col items-center justify-center"
      >
        <header class="text-6xl md:text-8xl font-bold">Profile</header>
        <div class="text-xl flex flex-col lg:flex-row pt-16 gap-8 items-center">
          {% if user.profile_image %}
          <img src="{{ user.profile_image.url }}" alt="Profile Picture" class="w-48 md:w-56 h-48 md:h-56">
          {% else %}
          <img src="{% static 'images/Logo.png' %}" alt="Profile Picture" class="w-32 md:w-48 h-32 md:h-48">
          {% endif %}
          <div class="text-center">
            <div class="flex flex-col">
              <p class="font-bold">Full Name:</p><p>Test User3</p>
            </div>
            <div class="flex flex-col">
              <p class="font-bold">Username:</p><p>TestUser3</p>
            </div>
            <div class="flex flex-col">
              <p class="font-bold">Email:</p><p>testuser3@gmail.com</p>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>

story_9/authentication/templates/authentication/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8" />
    <title>Authentication</title>
    <meta name="description" content="A simple authentication width Django" />
    <meta name="author" content="Teofanus Gary Setiawan" />

    <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;800&display=swap"
      rel="stylesheet"
    />

    <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'authentication/css/index.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'authentication/js/index.js' %}"></script>

    <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="icon" type="image/png" href="{% static 'images/Logo.png' %}" />
  </head>
  <body>
    {% if messages %} 
      {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
          {{ message }}
        </div>
      {% endfor %}
    {% endif %} 
    
    {% if register_form.errors %} 
      {% for field in register_form %} 
        {% for error in field.errors %}
          <div class="error">{{ error|escape }}</div>
        {% endfor %}
      {% endfor %} 

      {% for error in register_form.non_field_errors %}
        <div class="error">{{ error|escape }}</div>
      {% endfor %} 
    {% endif %}
    <div class="flex flex-col md:flex-row mx-8 md:mx-16 mb-8">
      <div
        class="light rounded-t-xl md:rounded-tr-none md:rounded-bl-xl flex flex-col gap-2 md:w-2/3 h-auto"
      >
        <header class="text-5xl pt-12 text-center">Sign In</header>
        <form
          action="{% url 'authentication:signin' %}"
          method="post"
          class="py-12 px-8 md:px-16"
        >
          {% csrf_token %}
          <div class="frm">
            {{ login_form.username.label_tag }}
            {{ login_form.username }}
          </div>

          <div class="frm">
            {{ login_form.password.label_tag }}
            {{ login_form.password }}
          </div>

          <div class="text-center">
            <input
              type="submit"
              value="Sign In"
              class="rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline"
            />
          </div>
        </form>
      </div>
      <div
        class="rounded-b-xl md:rounded-bl-none md:rounded-tr-xl flex flex-col gap-2 text-center justify-center py-8 md:py-48 md:w-1/3"
      >
        <p class="text-4xl">Hello!</p>
        <p>Haven't registered yet?</p>
        <a href="{% url 'authentication:signup' %}" id="signup">
          <button
            class="rounded-3xl px-6 py-2 focus:outline-none focus:border-blue-300 focus:shadow-outline signup"
          >
            Sign Up
          </button>
        </a>
      </div>
    </div>
  </body>
</html>

story_9/authentication/templates/authentication/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8" />
    <title>Authentication</title>
    <meta
      name="description"
      content="A simple authentication width Django"
    />
    <meta name="author" content="Teofanus Gary Setiawan" />

    <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;800&display=swap"
      rel="stylesheet"
    />

    <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link
      href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{% static 'authentication/css/index.css' %}"
      rel="stylesheet"
      type="text/css"
    />

    <!-- JS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'authentication/js/index.js' %}"></script>

    <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="icon" type="image/png" href="{% static 'images/Logo.png' %}" />
  </head>
  <body>
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="{{ message.tags }}" {% endif %}>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% if register_form.errors %}
        {% for field in register_form %}
            {% for error in field.errors %}
                <div class="error">
                    {{ error|escape }} 
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in register_form.non_field_errors %}
            <div class="error">
               {{ error|escape }}
            </div>
        {% endfor %}
    {% endif %}
    <div class="flex flex-col md:flex-row mx-8 md:mx-16 mb-8">
        <div class="flex flex-col gap-2 rounded-t-xl md:rounded-tr-none md:rounded-bl-xl text-center justify-center py-8 md:py-48 md:w-1/3">
            <p class="text-4xl">Hello!</p>
            <p>Already registered?</p>
            <a href="{% url 'authentication:signin' %}" id="signin">
                <button class="rounded-3xl px-6 py-2 focus:outline-none focus:border-blue-300 focus:shadow-outline signin">
                    Sign In
                </button>
            </a>
        </div>
        <div class="flex flex-col gap-2 rounded-b-xl md:rounded-bl-none md:rounded-tr-xl md:w-2/3 h-auto">
            <header class="text-5xl pt-12 text-center">Sign Up</header>
             <form action="{% url 'authentication:signup' %}" method="post" enctype="multipart/form-data" class="py-4 px-8 md:px-16">
                {% csrf_token %}
                <div class="frm">
                    {{ register_form.username.label_tag }}
                    {{ register_form.username }}
                </div>

                <div class="frm">
                    {{ register_form.email.label_tag }}
                    {{ register_form.email }}
                </div>

                <div class="flex gap-x-16">
                  <div class="frm w-1/2">
                    {{ register_form.first_name.label_tag }}
                    {{ register_form.first_name }}
                  </div>
                  <div class="frm w-1/2">
                    {{ register_form.last_name.label_tag }}
                    {{ register_form.last_name }}
                  </div>
                </div>

                <div class="frm">
                    {{ register_form.password1.label_tag }}
                    {{ register_form.password1 }}
                </div>

                <div class="frm">
                    {{ register_form.password2.label_tag }}
                    {{ register_form.password2 }}
                </div>

                <div class="frm">
                    {{ register_form.profile_image.label_tag }}
                    {{ register_form.profile_image }}
                </div>

                <div class="text-center">
                    <input type="submit" value="Sign Up" class="btn dark rounded-3xl py-2 px-6 focus:outline-none focus:border-blue-300 focus:shadow-outline">
                </div>
            </form>
        </div>
    </div>
  </body>
</html>